### PR TITLE
Update packet batching, UIX patch, EmulateVanilla option

### PR DESCRIPTION
**Pull request by Nytra**
- Adds EmulateVanilla option: Makes Unity sleep while FrooxEngine is running (Makes desktop mode feel much better)
- Patches UIX to use queued update packets: Fixes UIX breaking when using RenderIncompleteUpdates (I think)
- Batches completed updates from FrooxEngine: Can allow Unity to render multiple completed updates in one go

IMO this branch feels better than the current master, but I guess it needs testing still

### CODE REVIEW

**Comment by Nytra** [comment]
Side note: This reverts the ManualResetEvent stuff (Not intentional, it was a merge conflict because the branch is a bit old)

**Comment by DoubleStyx** [comment]
This is kind of hard to read. I'll try rebasing on top of main for readability. And then maybe the merge conflicts can be resolved.

**Comment by Nytra** [comment]
I did run a document reformat on the Thundagun.cs file which is why it looks like so much changed

**Comment by Nytra** [comment]
I realized I was rendering the incomplete updates before the completed ones, so i just fixed that

**Comment by DoubleStyx** [comment]
effectively merged. I guess I could've merged this directly, but I normalized the tabulation so the diff is more apparent for future reference.

**Pull request closed without merging**
