### PR TITLE
Add RenderContextOverride<T> and RenderMaterialOverride connector, update some other connectors

### PR DESCRIPTION
**Pull request by Nytra**
RenderMaterialOverride doesn't work yet but I think materials in general are somehow bugged (https://github.com/Frozenreflex/Thundagun/issues/8). Not sure how to fix that. I updated some other connectors to match the original code better.

### CODE REVIEW

**Comment by DoubleStyx** [comment]
Did you notice anything working after making these connector changes? Or is this just part of the goal to add the remaining connector behavior?

**Comment by Nytra** [comment]
The goal is to make the connectors match the base game as much as possible. Everything seemed to be working when I tested it, except for the RenderMaterialOverride which showed a pink material instead of the one specified in the component. RenderTransformOverride should now no longer crash people.

**Comment by DoubleStyx** [comment]
But the materialOverride wasn't working before either, right? As long as it's not a regression, feel free to merge. I tested it and everything seemed to work okay.

**Comment by DoubleStyx** [comment]
I'll go ahead and merge this as I didn't run into any immediate issues and since I've already published a separate release.

**Pull request merged**
